version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app/backend
    environment:
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/files:/app/backend/files
      - ./backend/tests:/app/backend/tests
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    working_dir: /app/frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

networks:
  default:
    driver: bridge
